# Generated by Django 5.1.3 on 2024-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_books_taken',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество книг, взятых пользователем', verbose_name='Количество взятых книг'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_days_held_books',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество дней, на которые книги были взяты пользователем', verbose_name='Общее количество дней использования книг'),
        ),
    ]
